### ISSUE TITLE
feature request: Cohen's d and Hedge's g for one-sample t-test

### ISSUE THREAD

**Issue by IndrajeetPatil** [mtorchiano/effsize#33]
As far as I can tell, this is currently not supported.

The syntax can look something like this, for example-
```r
treatment = rnorm(100,mean = 10)
control = rnorm(100,mean = 12)
cohen.d(~d, mu = 0)
```

**Comment by mtorchiano** [comment]
Working on it.

This is how it could work (using default mu=0)

```r
> treatment = rnorm(100,mean = 10)
> control = rnorm(100,mean = 12)
> cohen.d(~treatment, mu = 10)

Cohen's d (single sample)

d estimate: 0.0396593 (negligible)
Reference mu: 10
95 percent confidence interval:
     lower      upper 
-0.3572231  0.4365417 
> cohen.d(~control)

Cohen's d (single sample)

d estimate: 11.55047 (large)
Reference mu: 0
95 percent confidence interval:
    lower     upper 
 9.881998 13.218946 
```

**Comment by IndrajeetPatil** [comment]
This looks good in terms of the function syntax but the effect size values here are pretty different from what I am getting with our custom function or with other widely-used software like [JASP](https://jasp-stats.org/).

For example, here is `JASP` output for these two tests:

For `treatment` variable,

![image](https://user-images.githubusercontent.com/11330453/61591160-258b3b00-ab91-11e9-95f2-db3c541642fd.png)

**Comment by mtorchiano** [comment]
Sorry for looking back into it only now.

The new feature will be delivered soon.

The syntax is slightly different: `cohen.d(control~., mu = 10)`

Concerning the values, I'm not sure to what case you are referring to, if it is for the examples in the screenshots, you set two different reference mu, that's why you get so wildly different values.
